version: "3.1"
services:
#  api:
#    restart: unless-stopped
#    build: ./api/
#    working_dir: /usr/src/findmeplace/api
#    volumes:
#          - ./api:/usr/src/findmeplace/api
#    ports:
#     - "8080:8080"
#    command: mvn clean spring-boot:run
#    depends_on:
#      - db
  db:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: repoleved
      POSTGRES_DB: fmp_db
    ports:
      - "5432:5432"


