version: "3.1"
services:
  api:
    image: fmp_api
    build:
      context: ./api/
    ports:
     - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: repoleved
      POSTGRES_DB: fmp_db
    ports:
      - "5432:5432"


